// docs/proto/worker.proto — сгенерированный код -> common/api/protogen

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: orchestrator.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorAPI_SubmitWorkflow_FullMethodName       = "/worker.OrchestratorAPI/SubmitWorkflow"
	OrchestratorAPI_GetWorkflow_FullMethodName          = "/worker.OrchestratorAPI/GetWorkflow"
	OrchestratorAPI_CancelWorkflow_FullMethodName       = "/worker.OrchestratorAPI/CancelWorkflow"
	OrchestratorAPI_StreamWorkflowEvents_FullMethodName = "/worker.OrchestratorAPI/StreamWorkflowEvents"
)

// OrchestratorAPIClient is the client API for OrchestratorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorAPIClient interface {
	SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*SubmitWorkflowResponse, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowStatusResponse, error)
	CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error)
	StreamWorkflowEvents(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEvent], error)
}

type orchestratorAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorAPIClient(cc grpc.ClientConnInterface) OrchestratorAPIClient {
	return &orchestratorAPIClient{cc}
}

func (c *orchestratorAPIClient) SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*SubmitWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWorkflowResponse)
	err := c.cc.Invoke(ctx, OrchestratorAPI_SubmitWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorAPIClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowStatusResponse)
	err := c.cc.Invoke(ctx, OrchestratorAPI_GetWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorAPIClient) CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWorkflowResponse)
	err := c.cc.Invoke(ctx, OrchestratorAPI_CancelWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorAPIClient) StreamWorkflowEvents(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorAPI_ServiceDesc.Streams[0], OrchestratorAPI_StreamWorkflowEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetWorkflowRequest, WorkflowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorAPI_StreamWorkflowEventsClient = grpc.ServerStreamingClient[WorkflowEvent]

// OrchestratorAPIServer is the server API for OrchestratorAPI service.
// All implementations must embed UnimplementedOrchestratorAPIServer
// for forward compatibility.
type OrchestratorAPIServer interface {
	SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*SubmitWorkflowResponse, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowStatusResponse, error)
	CancelWorkflow(context.Context, *CancelWorkflowRequest) (*CancelWorkflowResponse, error)
	StreamWorkflowEvents(*GetWorkflowRequest, grpc.ServerStreamingServer[WorkflowEvent]) error
	mustEmbedUnimplementedOrchestratorAPIServer()
}

// UnimplementedOrchestratorAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorAPIServer struct{}

func (UnimplementedOrchestratorAPIServer) SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*SubmitWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWorkflow not implemented")
}
func (UnimplementedOrchestratorAPIServer) GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedOrchestratorAPIServer) CancelWorkflow(context.Context, *CancelWorkflowRequest) (*CancelWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWorkflow not implemented")
}
func (UnimplementedOrchestratorAPIServer) StreamWorkflowEvents(*GetWorkflowRequest, grpc.ServerStreamingServer[WorkflowEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamWorkflowEvents not implemented")
}
func (UnimplementedOrchestratorAPIServer) mustEmbedUnimplementedOrchestratorAPIServer() {}
func (UnimplementedOrchestratorAPIServer) testEmbeddedByValue()                         {}

// UnsafeOrchestratorAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorAPIServer will
// result in compilation errors.
type UnsafeOrchestratorAPIServer interface {
	mustEmbedUnimplementedOrchestratorAPIServer()
}

func RegisterOrchestratorAPIServer(s grpc.ServiceRegistrar, srv OrchestratorAPIServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorAPI_ServiceDesc, srv)
}

func _OrchestratorAPI_SubmitWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorAPIServer).SubmitWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorAPI_SubmitWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorAPIServer).SubmitWorkflow(ctx, req.(*SubmitWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorAPI_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorAPIServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorAPI_GetWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorAPIServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorAPI_CancelWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorAPIServer).CancelWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorAPI_CancelWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorAPIServer).CancelWorkflow(ctx, req.(*CancelWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorAPI_StreamWorkflowEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorAPIServer).StreamWorkflowEvents(m, &grpc.GenericServerStream[GetWorkflowRequest, WorkflowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorAPI_StreamWorkflowEventsServer = grpc.ServerStreamingServer[WorkflowEvent]

// OrchestratorAPI_ServiceDesc is the grpc.ServiceDesc for OrchestratorAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.OrchestratorAPI",
	HandlerType: (*OrchestratorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitWorkflow",
			Handler:    _OrchestratorAPI_SubmitWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _OrchestratorAPI_GetWorkflow_Handler,
		},
		{
			MethodName: "CancelWorkflow",
			Handler:    _OrchestratorAPI_CancelWorkflow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWorkflowEvents",
			Handler:       _OrchestratorAPI_StreamWorkflowEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator.proto",
}
