// docs/proto/worker.proto — сгенерированный код -> common/api/protogen

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: orchestrator.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskDefinition — то, что клиент присылает при создании workflow (соответствует §10.5 YAML один в один)].
type TaskDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DependsOn           []string               `protobuf:"bytes,2,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "shell" | "http" | ... — см. §6.4, executor registry
	Payload             map[string]string      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MaxRetries          int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	RetryBackoffSeconds int64                  `protobuf:"varint,6,opt,name=retry_backoff_seconds,json=retryBackoffSeconds,proto3" json:"retry_backoff_seconds,omitempty"`
	TimeoutSeconds      int64                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskDefinition) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *TaskDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskDefinition) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskDefinition) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TaskDefinition) GetRetryBackoffSeconds() int64 {
	if x != nil {
		return x.RetryBackoffSeconds
	}
	return 0
}

func (x *TaskDefinition) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SubmitWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tasks         []*TaskDefinition      `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowRequest) Reset() {
	*x = SubmitWorkflowRequest{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowRequest) ProtoMessage() {}

func (x *SubmitWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitWorkflowRequest) GetTasks() []*TaskDefinition {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SubmitWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowResponse) Reset() {
	*x = SubmitWorkflowResponse{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowResponse) ProtoMessage() {}

func (x *SubmitWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

// TaskStatusInfo — проекция domain.Task (§2) наружу: не весь Task целиком (там есть внутренние
// детали вроде AssignedTo, нужные только control-plane), а то, что осмысленно показать клиенту.
type TaskStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // PENDING | READY | DISPATCHED | RUNNING | SUCCEEDED | FAILED | RETRYING | CANCELLED
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // WorkerID, если уже назначена; пусто для PENDING/READY
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // заполнено, если status == FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusInfo) Reset() {
	*x = TaskStatusInfo{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusInfo) ProtoMessage() {}

func (x *TaskStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusInfo.ProtoReflect.Descriptor instead.
func (*TaskStatusInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *TaskStatusInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskStatusInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskStatusInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatusInfo) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *TaskStatusInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskStatusInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WorkflowStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // PENDING | RUNNING | SUCCEEDED | FAILED | CANCELLED
	Tasks         []*TaskStatusInfo      `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatusResponse) Reset() {
	*x = WorkflowStatusResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusResponse) ProtoMessage() {}

func (x *WorkflowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowStatusResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStatusResponse) GetTasks() []*TaskStatusInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *CancelWorkflowResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// WorkflowEvent — одна запись в потоке StreamWorkflowEvents. task_id пустой для событий
// уровня всего workflow (например WORKFLOW_STATUS_CHANGED -> SUCCEEDED).
type WorkflowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "TASK_STATUS_CHANGED" | "WORKFLOW_STATUS_CHANGED"
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix-время на лидере, проставляется ПРИ ЗАПИСИ команды в Raft-лог (§3.5,
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkflowEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WorkflowEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// LeaderHint — детали gRPC-ошибки "not leader" (§10.2): follower подсказывает клиенту,
// на какой адрес реально стоит повторить запрос.
type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderAddress string                 `protobuf:"bytes,1,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *LeaderHint) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x06worker\"\xd0\x02\n" +
	"\x0eTaskDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x02 \x03(\tR\tdependsOn\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12=\n" +
	"\apayload\x18\x04 \x03(\v2#.worker.TaskDefinition.PayloadEntryR\apayload\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x122\n" +
	"\x15retry_backoff_seconds\x18\x06 \x01(\x03R\x13retryBackoffSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x03R\x0etimeoutSeconds\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x15SubmitWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05tasks\x18\x02 \x03(\v2\x16.worker.TaskDefinitionR\x05tasks\"9\n" +
	"\x16SubmitWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"5\n" +
	"\x12GetWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\x9d\x01\n" +
	"\x0eTaskStatusInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\x04 \x01(\tR\n" +
	"assignedTo\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x93\x01\n" +
	"\x16WorkflowStatusResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12,\n" +
	"\x05tasks\x18\x04 \x03(\v2\x16.worker.TaskStatusInfoR\x05tasks\"8\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"4\n" +
	"\x16CancelWorkflowResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"0\n" +
	"\x12CancelTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x9e\x01\n" +
	"\rWorkflowEvent\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"3\n" +
	"\n" +
	"LeaderHint\x12%\n" +
	"\x0eleader_address\x18\x01 \x01(\tR\rleaderAddress2\x90\x03\n" +
	"\x0fOrchestratorAPI\x12O\n" +
	"\x0eSubmitWorkflow\x12\x1d.worker.SubmitWorkflowRequest\x1a\x1e.worker.SubmitWorkflowResponse\x12I\n" +
	"\vGetWorkflow\x12\x1a.worker.GetWorkflowRequest\x1a\x1e.worker.WorkflowStatusResponse\x12O\n" +
	"\x0eCancelWorkflow\x12\x1d.worker.CancelWorkflowRequest\x1a\x1e.worker.CancelWorkflowResponse\x12C\n" +
	"\n" +
	"CancelTask\x12\x19.worker.CancelTaskRequest\x1a\x1a.worker.CancelTaskResponse\x12K\n" +
	"\x14StreamWorkflowEvents\x12\x1a.worker.GetWorkflowRequest\x1a\x15.worker.WorkflowEvent0\x01B\x15Z\x13common/api/protogenb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_orchestrator_proto_goTypes = []any{
	(*TaskDefinition)(nil),         // 0: worker.TaskDefinition
	(*SubmitWorkflowRequest)(nil),  // 1: worker.SubmitWorkflowRequest
	(*SubmitWorkflowResponse)(nil), // 2: worker.SubmitWorkflowResponse
	(*GetWorkflowRequest)(nil),     // 3: worker.GetWorkflowRequest
	(*TaskStatusInfo)(nil),         // 4: worker.TaskStatusInfo
	(*WorkflowStatusResponse)(nil), // 5: worker.WorkflowStatusResponse
	(*CancelWorkflowRequest)(nil),  // 6: worker.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil), // 7: worker.CancelWorkflowResponse
	(*CancelTaskRequest)(nil),      // 8: worker.CancelTaskRequest
	(*CancelTaskResponse)(nil),     // 9: worker.CancelTaskResponse
	(*WorkflowEvent)(nil),          // 10: worker.WorkflowEvent
	(*LeaderHint)(nil),             // 11: worker.LeaderHint
	nil,                            // 12: worker.TaskDefinition.PayloadEntry
}
var file_orchestrator_proto_depIdxs = []int32{
	12, // 0: worker.TaskDefinition.payload:type_name -> worker.TaskDefinition.PayloadEntry
	0,  // 1: worker.SubmitWorkflowRequest.tasks:type_name -> worker.TaskDefinition
	4,  // 2: worker.WorkflowStatusResponse.tasks:type_name -> worker.TaskStatusInfo
	1,  // 3: worker.OrchestratorAPI.SubmitWorkflow:input_type -> worker.SubmitWorkflowRequest
	3,  // 4: worker.OrchestratorAPI.GetWorkflow:input_type -> worker.GetWorkflowRequest
	6,  // 5: worker.OrchestratorAPI.CancelWorkflow:input_type -> worker.CancelWorkflowRequest
	8,  // 6: worker.OrchestratorAPI.CancelTask:input_type -> worker.CancelTaskRequest
	3,  // 7: worker.OrchestratorAPI.StreamWorkflowEvents:input_type -> worker.GetWorkflowRequest
	2,  // 8: worker.OrchestratorAPI.SubmitWorkflow:output_type -> worker.SubmitWorkflowResponse
	5,  // 9: worker.OrchestratorAPI.GetWorkflow:output_type -> worker.WorkflowStatusResponse
	7,  // 10: worker.OrchestratorAPI.CancelWorkflow:output_type -> worker.CancelWorkflowResponse
	9,  // 11: worker.OrchestratorAPI.CancelTask:output_type -> worker.CancelTaskResponse
	10, // 12: worker.OrchestratorAPI.StreamWorkflowEvents:output_type -> worker.WorkflowEvent
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
